### ISSUE TITLE
CSS position and button triggers form submit

### ISSUE THREAD

**Issue by q2apro** [benwinding/quill-html-edit-button#1]
**1. CSS Bug**

textarea is positioned absolutely and results in:

![image](https://user-images.githubusercontent.com/6764548/69331892-35f61400-0c5e-11ea-87d2-3928436afba7.png)

Fix: `left:15px;`

Additionally, please add CSS classes to the `div`s of the plugin to be targetted!

**2. JS Bug**

When I hit the "HTML" button, the form that holds the editor gets submitted. Please change the code:

`button.onclick = function (e) {\n   e.preventDefault();   launchPopupEditor(quill);`

Thanks!

**Comment by benwinding** [comment]
Thanks again for your fixes!

Deployed in version `1.0.4`
