### ISSUE TITLE
Can not read property 'emit' of undefined

### ISSUE THREAD

**Issue by danghung1202** [benwinding/quill-html-edit-button#12]
Using the demo link:
https://benwinding.github.io/quill-html-edit-button/src/demo.html

Paste the html to update the content

```html
<div class="boxed" style="color:#ff0000;"><strong>Translations:</strong> Can you help translate this site into a foreign language ? Please email us with details if you can help.</div>
```

The actual result: The editor's content is blank and the console show the error

```
Uncaught TypeError: Cannot read property 'emit' of undefined
    at e.value (scroll.js:158)
    at MutationObserver.<anonymous> (scroll.ts:29)
```

**Comment by benwinding** [comment]
Thanks for reporting this @danghung1202,
It's weird, as it seems like Quill doesn't like divs. 
This can also be reproduced with a simpler case... by inserting a div into the html editor
``` html
<div>THIS CRASHES</div>
```
I'm looking into this right now.
Cheers,
Ben

**Comment by danghung1202** [comment]
Thanks @benwinding for fixed this quickly.

**Comment by benwinding** [comment]
No worries,
It's fixed now, just update to the latest package to use it.
Seems that Quill can't use div tags out of the box. So it's fixed within this library using the following patch from a related issue:  https://github.com/quilljs/quill/issues/2040#issuecomment-441413485 
Thanks for checking out the project.
Cheers,
Ben
