### ISSUE TITLE
ReferenceError: Quill is not defined

### ISSUE THREAD

**Issue by leixuesong** [benwinding/quill-html-edit-button#13]
![image](https://user-images.githubusercontent.com/6357885/86874838-c9a82200-c113-11ea-91d0-1a88b1fd7fb9.png)

![image](https://user-images.githubusercontent.com/6357885/86874803-b4cb8e80-c113-11ea-8013-a9861b65c4d8.png)

**Comment by leixuesong** [comment]
window.Quill = Quill

**Comment by Haris3243** [comment]
> window.Quill = Quill

where to add this line

**Comment by henrik-d** [comment]
> > window.Quill = Quill
> 
> where to add this line??
> @leixuesong

@Haris3243 This works for me:
```
import Quill from 'quill'
import htmlEditButton from "quill-html-edit-button";

window.Quill = Quill;
Quill.register('modules/htmlEditButton', htmlEditButton);
```

**Comment by scorsi** [comment]
This shall be documented in the README :)
