### ISSUE TITLE
[Enhancement] Syntax highlighting

### ISSUE THREAD

**Issue by TheSharpieOne** [benwinding/quill-html-edit-button#15]
First, thanks for this library it was exactly what I needed.

Since the user is always editing HTML in the modal, it would be nice to have syntax highlighting enable for that editor.
I would imagine since quill is already being used and since it can support syntax highlighting, that it might be possible to just use another quill instance as the HTML editor with syntax highlighting enabled. Of course this would be an option exposed so that developers who do not want to include highlight.js to not have syntax highlighting.

**Comment by benwinding** [comment]
Hi @TheSharpieOne,
Thanks for checking out the project. Yeah that's a good idea, and something I've been thinking about for a while. 
It already has some indentation that is applied to the HTML (although it's not always pretty), syntax highlighting would be a nice addition:
![image](https://user-images.githubusercontent.com/11782590/91373396-7326ac80-e855-11ea-8519-cabdf8004ba5.png)
Are you familiar with `highlight.js`? You can submit a PR with this feature as an option if you like :+1: 
Cheers,
Ben
