### ISSUE TITLE
[Bug] Spaces are removed when tags are next to each other

### ISSUE THREAD

**Issue by TheSharpieOne** [benwinding/quill-html-edit-button#18]
Caused by the fix for #6 the solution broke how spaces are handled between tags. The spaces are removed and tags get butted up next to one another:
![Kapture 2020-08-27 at 14 46 41](https://user-images.githubusercontent.com/664714/91482756-90b73e80-e874-11ea-8a21-6b8b52952164.gif)

**Comment by Saltibarsciai** [comment]
re-open
