### ISSUE TITLE
CSS into separate file, not into JS

### ISSUE THREAD

**Issue by q2apro** [benwinding/quill-html-edit-button#2]
In JS there is: `popupContainer.setAttribute("style", "background: #ddd; position: absolute; ` ...

This should go into a separate file. Please use CSS classes and IDs. Thanks.

**Comment by benwinding** [comment]
This was hacked together in a couple of hours, not sure how to include css files in the bundle. Are you able to make a PR for this one?

Thanks for your help,

**Comment by q2apro** [comment]
Okay, I see. Better workaround: 

1. Create the dynamic elements with ID and CLASS.

2. Using JS, in the end of your code, add CSS to the head (insert `<style>...</style>`), which holds the CSS according to ID and CLASS set under n°1.
