### ISSUE TITLE
Not working with vue.js

### ISSUE THREAD

**Issue by Haris3243** [benwinding/quill-html-edit-button#21]
I have imported it and used  it as follows in my vue.js code which already uses vue-quill-editor
```
import htmlEditButton from "quill-html-edit-button";
Quill.register("modules/htmlEditButton", htmlEditButton);
```
and in modules i have pasted folowing code
```
 htmlEditButton: {
              debug: true,
              msg: 'Edit the content in HTML format',
              okText: 'Ok',
              cancelText: 'Cancel',
              buttonHTML: '&lt;&gt;',
              buttonTitle: 'Show HTML source',
              syntax: false,
            },
```

But is not showing <> in the output. Output is as follows
![image](https://user-images.githubusercontent.com/43663314/93853398-3e2f3d80-fccd-11ea-89fa-d2433ff577d1.png)

@benwinding sir Please help me as soon as you can

**Comment by benwinding** [comment]
Hello @Haris3243,
Apologies for the late response, did you place the `Quill` import at the top? 

```
import Quill from 'quill'
import htmlEditButton from "quill-html-edit-button";
Quill.register("modules/htmlEditButton", htmlEditButton);
```

More information in the `vue-quill-editor` docs here: https://github.com/surmon-china/vue-quill-editor#register-quill-module

Cheers,
Ben

**Comment by buxianghenishuohua** [comment]
htmlEditButton: {
              debug: true,
              msg: 'Edit the content in HTML format',
              okText: 'Ok',
              cancelText: 'Cancel',
              buttonHTML: '&lt;&gt;',
              buttonTitle: 'Show HTML source',
              syntax: false,
            }

**Comment by Aaron-9338** [comment]
htmlEditButton: {
              debug: true,
              msg: 'Edit the content in HTML format',
              okText: 'Ok',
              cancelText: 'Cancel',
              buttonHTML: '&lt;&gt;',
              buttonTitle: 'Show HTML source',
              syntax: false,
            }

Where is this added? I am a Vue3 project and I have been trying to get errors all along？help
