### ISSUE TITLE
Doesn't render tables 

### ISSUE THREAD

**Issue by unkn0wn-developer** [benwinding/quill-html-edit-button#22]
Hi, this plugin doesn't render tables if I placed something like below.

It just disappears as soon as I hit "OK" and the code is gone.

``` html
<table>
  <tr>
    <th>Company</th>
    <th>Contact</th>
    <th>Country</th>
  </tr>
  <tr>
    <td>Alfreds Futterkiste</td>
    <td>Maria Anders</td>
    <td>Germany</td>
  </tr>
  <tr>
    <td>Centro comercial Moctezuma</td>
    <td>Francisco Chang</td>
    <td>Mexico</td>
  </tr>
  <tr>
    <td>Ernst Handel</td>
    <td>Roland Mendel</td>
    <td>Austria</td>
  </tr>
  <tr>
    <td>Island Trading</td>
    <td>Helen Bennett</td>
    <td>UK</td>
  </tr>
  <tr>
    <td>Laughing Bacchus Winecellars</td>
    <td>Yoshi Tannamuri</td>
    <td>Canada</td>
  </tr>
  <tr>
    <td>Magazzini Alimentari Riuniti</td>
    <td>Giovanni Rovelli</td>
    <td>Italy</td>
  </tr>
</table>
```

**Comment by benwinding** [comment]
Hi @unkn0wn-developer,
This library currently only supports Quill 1.x which doesn't support tables.
From the looks of it Quill 2.x _does_ support tables, so we might update it to support them.
Cheers,
Ben

**Comment by unkn0wn-developer** [comment]
> Hi @unkn0wn-developer,
> This library currently only supports Quill 1.x which doesn't support tables.
> From the looks of it Quill 2.x _does_ support tables, so we might update it to support them.
> Cheers,
> Ben

Hi @benwinding ,

Thanks for your fast reply.
We've been looking for a WYSIWYG text editor with table support. We found out that all the other options have either too many dependencies or 463 open issues on their project page with lacking maintenance.

We thought that we would maybe give our users an option to add their tables directly using the HTML code (using this plugin) instead of relying on third-party quill js table plugin which also has over 100 open issues.

This plugin seemed simple to use without being too hard or complex to maintain (for security and other potential future issues.) That's why I've been looking into it today.

Anyway, thanks again.
- Dave

**Comment by benwinding** [comment]
> We found out that all the other options have either too many dependencies or 463 open issues on their project page with lacking maintenance.

Yes I know the feeling. Many other open-source _WYSIWYG_ editors are convoluted and mostly broken, one of the reasons why I like Quill is it's simplicity and easy plugin system.

Try this quill plugin [quill-better-table](https://github.com/soccerloway/quill-better-table), looks like it supports tables in quill, they also have a demo here too: https://codepen.io/soccerloway/pen/WWJowj

This package might work with Quill 2.x but I haven't tested it yet.

**Comment by benwinding** [comment]
Tables are working! 

You just need to use Quill 2.x, at this time the latest version is `2.0.0-dev.4`

![Peek 2020-10-07 09-20](https://user-images.githubusercontent.com/11782590/95268209-6185eb00-087e-11eb-8f10-c86514dc151e.gif)
