### ISSUE TITLE
Disabling tab key 

### ISSUE THREAD

**Issue by kamleshpawar2006** [benwinding/quill-html-edit-button#29]
Hi, there is no provision to add tab key event. The main Quill editor has this;
`keyboard: {
      bindings: {
        tab: {
          key: 9,
          handler: function() {
            return true;
          }
        }
      }
    },`
is there a way we can implement in HTML editor as well.

**Comment by benwinding** [comment]
No problem, you should be able to add any custom modules to the HTML editor quill instance. 

Just add the `editorModules` field to the options like this:

``` js
  htmlEditButton: {
    // ...
    editorModules: {
      // Any modules here will be declared in HTML quill editor instance
      keyboard: {
        bindings: {
          custom: {
            key: 'a',
            handler: function(range, context) {
              console.log('A KEY PRESSED!');
            }
          },
        },
      },
    },
  },
```
Deployed in version `quill-html-edit-button@2.0.6`

**Comment by kamleshpawar2006** [comment]
I tried this solution, it works fine for all alphabet keys and enter key, but doesn't work for tab key.
