### ISSUE TITLE
Use icon for Button instead of label "HTML"

### ISSUE THREAD

**Issue by q2apro** [benwinding/quill-html-edit-button#3]
This is just a suggestion, because all quill buttons seem to be with icons.

Instead of "HTML"  you might want to use: 

`button.innerHTML = "&lt;&gt;";`

Resulting in:

![image](https://user-images.githubusercontent.com/6764548/69332248-f3810700-0c5e-11ea-9acb-3c8bf97c465e.png)

You also might want to add a tooltip:

`button.title = "Show HTML source";`

![image](https://user-images.githubusercontent.com/6764548/69332436-5d99ac00-0c5f-11ea-8a02-666c276b1e05.png)

**Comment by benwinding** [comment]
Thanks for your input, I agree that's a bit nicer on the eyes.

Deployed in version `1.0.2`
