### ISSUE TITLE
Doesn't work with big documents

### ISSUE THREAD

**Issue by MrFishchev** [benwinding/quill-html-edit-button#31]
It totally crashes the web page, if I trying to edit document with ~2500 words.

**Comment by benwinding** [comment]
Hi @MrFishchev 
Can you please post some more information to help reproduce the problem:
- browser console output
- test text, which causes the crash

Cheers, 
Ben

**Comment by benwinding** [comment]
Please try with Quill version 2.x, it seems to be much faster. 

**Quill 1.x**
![image](https://user-images.githubusercontent.com/11782590/100731191-f9392d00-341a-11eb-9cd0-156bfb0328ed.png)

**Quill 2.x (32 times faster!)**
![image](https://user-images.githubusercontent.com/11782590/100731301-1e2da000-341b-11eb-8468-9201417385ef.png)

This is the bottle neck here:
https://github.com/benwinding/quill-html-edit-button/blob/9401118724bff2049094224847808ef92d096d9c/src/quill.htmlEditButton.ts#L120-L127

**Comment by riyastir** [comment]
Where is Quill 2.x?

**Comment by benwinding** [comment]
Version `2.0.0-dev.4` (not released as latest version yet), Here's a demo
https://github.com/benwinding/quill-html-edit-button/blob/master/src/demo-script-tag-2.x.html
Still in active development, but should be released soon I hope
