### ISSUE TITLE
Can set widht display auto word-break, so user not need scroll right

### ISSUE THREAD

**Issue by ikhun** [benwinding/quill-html-edit-button#32]
im sorry for my engglish, maybe easy explain with image.

![image](https://user-images.githubusercontent.com/42758127/100312949-25514a00-2fe6-11eb-9f9e-1b61939aace3.png)
this my expectation

![image](https://user-images.githubusercontent.com/42758127/100313026-4dd94400-2fe6-11eb-9df6-bfefbf88124d.png)
and this is the quil-html-edit button view

**Comment by benwinding** [comment]
Hi @ikhun,
That's okay, I understand you. Alright I'll have a look at changing that.
Ben

**Comment by benwinding** [comment]
This looks a bit easier to work with
![image](https://user-images.githubusercontent.com/11782590/100315250-4460d380-3008-11eb-8e3c-30086725d740.png)

**Comment by ikhun** [comment]
thankyou @benwinding for update, im new in vue and node module so must learn more again.
