### ISSUE TITLE
Not able to access tab key

### ISSUE THREAD

**Issue by kamleshpawar2006** [benwinding/quill-html-edit-button#35]
Hello,

@JuanCrg90 
I tried implementation suggested in issue [#29](https://github.com/benwinding/quill-html-edit-button/issues/29) or [https://github.com/benwinding/quill-html-edit-button#customising-the-editor](https://github.com/benwinding/quill-html-edit-button#customising-the-editor). But it does not work specifically for tab key.

Thanks

**Comment by benwinding** [comment]
Hi @kamleshpawar2006,

This doesn't seem to be possible and is an issue in the Quill editor, not this module.

More details here: https://github.com/quilljs/quill/issues/1967

Cheers,
Ben
