### ISSUE TITLE
File not found:'quill.js' 

### ISSUE THREAD

**Issue by gruming** [benwinding/quill-html-edit-button#36]
hello,

First of all, thank you for making a nice library ^^

An error occurs like the following text.

```
./node_modules/quill-html-edit-button/dist/quill.htmlEditButton.min.js
File not found:'quill.js' does not match its name on disk:'./node_modules/Quill/dist/quill'.
```

My development environment is using ReactJS + react-quill + quill.

Looking at my node module folder structure, it has a structure in the form of'./node_modules/quill/dist/quill', is there any solution?

**Comment by benwinding** [comment]
Closed by #37 
Should be available as `quill-html-edit-button@2.1.0` 
Hopefully it fixes the issue, and thanks for reporting the issue!
Cheers,
Ben
