### ISSUE TITLE
This library has a fatal JS bug (live demos currently not loading)

### ISSUE THREAD

**Issue by GJMichael** [benwinding/quill-html-edit-button#39]
Hi,

Just imported this library into a project and haven't been able to get it working. Then realised that the live demos also have the same bug:
https://benwinding.github.io/quill-html-edit-button/src/demo.html
https://benwinding.github.io/quill-html-edit-button/src/demo-script-tag.html

Firefox error:
![image](https://user-images.githubusercontent.com/39684379/104860960-742db700-5979-11eb-80d3-f49e2eba3ace.png)

Chrome error:
![image](https://user-images.githubusercontent.com/39684379/104861003-bb1bac80-5979-11eb-9e1a-a38156616481.png)

Anyone have any ideas on how to fix this?

Thanks!

**Comment by benwinding** [comment]
Hi @GJMichael,

Yes, this is a result of a broken PR #37 . Just roll back to version  2.0.x for now, and I'll close out this issue once it's fixed.

Cheers,
Ben

**Comment by GJMichael** [comment]
Thanks mate, version 2.0.9 works fine.

**Comment by benwinding** [comment]
Hi @GJMichael,

Try using version `2.2.0` now if you like. I've removed the external reference and added a lot of demos, including the following:

- [Live Demo (webpack javascript)](https://benwinding.github.io/quill-html-edit-button/src/demos/javascript/demo.html) - also > [Source Code](src/demos/javascript)
- [Live Demo (webpack typescript)](https://benwinding.github.io/quill-html-edit-button/src/demos/typescript/demo.html) - also > [Source Code](src/demos/typescript)
- [Live Demo (script tags quill-1.x)](https://benwinding.github.io/quill-html-edit-button/src/demos/script-tags/demo-quill-1.x.html) - also > [Source Code](src/demos/script-tags/demo-quill-1.x.html)
- [Live Demo (script tags quill-2.x) With Tables!](https://benwinding.github.io/quill-html-edit-button/src/demos/script-tags/demo-quill-2.x.html) - also > [Source Code](src/demos/script-tags/demo-quill-2.x.html)

Let me know how you go.

Cheers,
Ben

**Comment by GJMichael** [comment]
Thanks mate, all works now.
