### ISSUE TITLE
Update on the html editor does not trigger any quill output event 

### ISSUE THREAD

**Issue by mario-alva** [benwinding/quill-html-edit-button#41]
I'm trying to use the package on an Angular 10 app, implementing it via Typescript.

After you open the pop up for the html editing, do some html changes and click Ok. That model update does not trigger any output event on the quill editor. 

Tried catching the model update using the following methods:
`(onEditorChanged)="onEditorChanged($event)"
(onContentChanged)="onContentChanged($event)"
(onBlur)="onBlur($event)"
(onTextChanged)="onTextChanged($event)"`

Also tried with:
`(ngModelChange)="onModelChanged($event)"` but it is inconsistent, sometimes the update triggers this onModelChanged, but not all the time.

What would be the right way to capture that model update after you change the html and click Ok? What I need is to capture that new value that the quill editor has now.

Thanks.

**Comment by benwinding** [comment]
Hi @mario-alva & @zhnoah
Try the latest version of the package `2.2.3` I've changed the HTML update method it now uses the following code:
``` js
quill.clipboard.dangerouslyPasteHTML(html);
```
This will probably trigger one of those angular output events, but I don't know which one.
Let me know how it goes!
Cheers,
Ben
