### ISSUE TITLE
No way to include a script tag?

### ISSUE THREAD

**Issue by awunder** [benwinding/quill-html-edit-button#43]
i wanted to use this on an admin backend edit function but i cant seem to include script tags..

is there a way to allow everything i could paste in there?

**Comment by benwinding** [comment]
Not sure Quill allows putting arbitrary script tags in the editor.

See this issue for more details:
https://github.com/quilljs/quill/issues/2048

**Comment by sehgalmayank001** [comment]
@benwinding , is there a way to support inline styling & style tags?

**Comment by benwinding** [comment]
> is there a way to support inline styling & style tags?

Some basic inline styles are supported but not all, see gif below.

![Peek 2021-04-23 12-45](https://user-images.githubusercontent.com/11782590/115813224-f5419200-a431-11eb-8f8a-4b445b492dce.gif)

Closing this issue for now as it's related to the base quill library (see: quilljs/quill#2048), not this package.

**Comment by sehgalmayank001** [comment]
@benwinding , I tried the same thing as you, but still in vain.

https://user-images.githubusercontent.com/29652266/115865327-cb01cb80-a455-11eb-8cc5-852c26b0c1bc.mov
