### ISSUE TITLE
Table support 

### ISSUE THREAD

**Issue by Ricardo-Guia** [benwinding/quill-html-edit-button#44]
Hi everyone,

So the issue is when i paste a table  with : 
![image](https://user-images.githubusercontent.com/51034291/115705175-23f13700-a364-11eb-8f55-c403442e1922.png)

the result is :
![image](https://user-images.githubusercontent.com/51034291/115705250-3cf9e800-a364-11eb-99e1-a82c141e3f08.png)

**Comment by benwinding** [comment]
The table support in quill is very basic at the moment (see this issue: https://github.com/quilljs/quill/issues/117)

For now it seems `<thead>` is not supported correctly, I'll close this as it's not an issue with this library directly.
