### ISSUE TITLE
Modified style does not take effect

### ISSUE THREAD

**Issue by szx654038096** [benwinding/quill-html-edit-button#46]
Hello,First of all, thank you very much for having such a good work,I have a little problem,I modified the source code after editing, and the effect of adding styles to the text does not take effect. Do you know how to solve it?
Looking forward to your reply,Thank you very much

**Comment by benwinding** [comment]
Hi @szx654038096,

There's only a few supported HTML styles in the Quill editor. Basically quill uses CSS classes to represent inline styles. And quill converts inline styles to use these classes, as this issue explains: (https://github.com/quilljs/quill/issues/1451#issuecomment-523559508).

Try adding a few styles like `font-weight: bold;` or `font-style: italic` they should work fine. Others like `color: red`, might not work unless the **attributors** are added like this issue explains: (https://github.com/quilljs/quill/issues/1274) 

And if there's a style that doesn't have an attributor you can add your own, as shown here: (https://github.com/quilljs/quill/issues/1274#issuecomment-303619625)

Cheers,
Ben
