### ISSUE TITLE
script tag example doesn't work on my site

### ISSUE THREAD

**Issue by Valentine13** [benwinding/quill-html-edit-button#48]
I'm just trying to replicate your [example](https://benwinding.github.io/quill-html-edit-button/src/demos/script-tags/demo-quill-2.x.html)
on my site, but the console throws the error "Uncaught TypeError: Cannot read property 'import' of undefined". What am I doing wrong?(
My test page is here: [test](https://www.ermolova.ru/renovation/templates/texteditor-2.html)

**Comment by benjaminvanrenterghem** [comment]
I had the same problem.
Use this instead (from the linked github.io page): 
https://benwinding.github.io/quill-html-edit-button/dist/quill.htmlEditButton.min.js

And add these as well:
https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/styles/github.min.css
https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/highlight.min.js
https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/languages/xml.min.js

**Comment by benwinding** [comment]
Hey Guys,

Fixed a couple of things and made the script-tag demos work using newest version. 

Just download one of these files and they should just run in the browser as expected.
- Quill 1.x - https://github.com/benwinding/quill-html-edit-button/blob/master/src/demos/script-tags/demo-quill-1.x.html
- Quill 2.x - https://github.com/benwinding/quill-html-edit-button/blob/master/src/demos/script-tags/demo-quill-2.x.html

Let me know if there's any issues 👍
