### ISSUE TITLE
Enhancement: Line breaks after each closing tag

### ISSUE THREAD

**Issue by q2apro** [benwinding/quill-html-edit-button#5]
Obivously, quill puts all HTML into one line, which makes it hard to read.

As an idea: The html-edit-plugin could add line breaks after each closing HTML tag, such as `</p>`.

This would increase the readability a lot.

**Comment by benwinding** [comment]
Good point, I agree. This wasn't entirely trivial, but I got it working.

![image](https://user-images.githubusercontent.com/11782590/69397796-82615280-0d37-11ea-8d70-5d4d81dcb2c2.png)

Deployed in version `1.0.5`
