### ISSUE TITLE
Window is not editable with buttons misaligned 

### ISSUE THREAD

**Issue by peterlaws** [benwinding/quill-html-edit-button#52]
I'm not sure what I'm doing wrong.

I think I've all the correct JS and CSS added and in the correct order.
The window opens, however, I'm unable to edit within the window and the 'Ok' and 'Cancel' buttons are misaligned although both work (closes the window).

Screenshot https://imgur.com/WGKcAPe

**Comment by peterlaws** [comment]
This is to do when using the WYSIWYG in a Bootstrap modal. However, I see a fix for TinyMCE but it doesn't work for me.
Fix was
```
document.addEventListener('focusin', function(e) {
if (e.target.closest(".tox-tinymce-aux, .moxman-window, .tam-assetmanager-root") !== null) {
		e.stopImmediatePropagation();
	  }
});
```
But I did try TinyMCE, yet, the source pop-up was not focused......

**Comment by benwinding** [comment]
Hey @peterlaws,
Sounds weird, are you able to do the following to help me solve your issue:
- Tell me the version of, `quill` `quill-html-edit-button` and browser version you are using?
- Can you show a small amount of source-code that can reproduce the problem?

Also TinyMCE is a totally different WYSIWYG right? This requires the `quill` library

**Comment by peterlaws** [comment]
I understand this uses Quill library, was just checking other WYSIWYGs to see if I get the same outcome, and indeed I do - so either it's the template I'm using or something else

I'm using this tempate/etc https://github.com/DashboardPack/architectui-html-theme-free - Bootstrap 5 3, jQuery 3.6.5

Quill v1.3.7
Edit button v2.2.7

**Comment by benwinding** [comment]
That dashboard template uses many different npm libraries, and it looks like some are stepping on each other's toes. 

Looks like it could be a global CSS problem, You can use Chrome dev tools to determine what is being overridden by which library.

![image](https://user-images.githubusercontent.com/11782590/145693825-1a83c6fa-7745-47db-8776-ab004da27170.png)

And if other editors have the same problem, then it's likely that another library is globally overriding the CSS somewhere. Or setting the div to `contenteditale=false`

![image](https://user-images.githubusercontent.com/11782590/145693794-9038fca4-0091-48d3-b559-80458f39dc34.png)

**Comment by peterlaws** [comment]
It's not that, it must be the Bootstrap Modal. 

Tested a form and Quill on a blank page with the template, and...... guess what...... works like a charm, although the 'Ok' and 'Cancel' buttons still overlap the textarea.

I thought I was being clever by using a Modal, but I guess someone wants to lead me to believe I am stupid!

**Comment by peterlaws** [comment]
I have to go with CKEditor, which has a built-in 'view-source' that displays within the actual area and not in a pop-up.

Such a shame.

Thanks for the help @benwinding
