### ISSUE TITLE
Tags eliminated

### ISSUE THREAD

**Issue by bobitza** [benwinding/quill-html-edit-button#54]
i have this link and want to add the i tag, but output is without
`<a href="#" class="stretched-link btn p-0 fw-semibold"><u>View Details</u> <i class="icon-line-arrow-right position-relative ms-1" style="top: 2px"></i></a>`

**Comment by bobitza** [comment]
The output:
`    <a href="#" rel="noopener noreferrer" target="_blank"> 
      <u>
        View Details
      </u>
    </a> `

**Comment by benwinding** [comment]
Is that an icon or something?
This `<i></i>` tag is treated as a `italic` when inserted into Quill and it has no `innerText` so it's removed.

**Comment by bobitza** [comment]
<i> tag is used like icon for font-awesome ex <i class="fa fa-user"></i>

**Comment by bobitza** [comment]
+ style attribute and class removed from tags

**Comment by benwinding** [comment]
So Quill doesn't use HTML to represent the input, it uses a [Delta representation](https://quilljs.com/docs/delta/) which is a JSON format rendered as HTML.

This library effectively just passes the HTML to Quill, as shown in the source below:

https://github.com/benwinding/quill-html-edit-button/blob/a269151e88bb7768dee1076512de522919215bf4/src/quill.htmlEditButton.ts#L38-L40

Some classes are supported by Quill internally eg: ql-bg-yellow ([Demo here](https://codepen.io/quill/pres/jrvpQL))
![image](https://user-images.githubusercontent.com/11782590/156862344-538534ae-7a96-4872-b207-b152409d9fcd.png)

But custom classes are not recognised, and I'm not sure of how to allow them. ([Demo here](https://codepen.io/quill/pen/dMQGmq))
![image](https://user-images.githubusercontent.com/11782590/156862172-297c5098-5012-486a-903f-ab4550837635.png)

**Comment by bobitza** [comment]
Ok thanks
