### ISSUE TITLE
is this package still supported , getting errors  using on vue 3

### ISSUE THREAD

**Issue by Taekondainc** [benwinding/quill-html-edit-button#55]
``icon wont show or work

vue: 3
vscode
js

 
![Screenshot (29)](https://user-images.githubusercontent.com/46072451/158877580-88f13fff-57bd-4517-8dca-9f5cbf1ff08f.png)
![Screenshot (30)](https://user-images.githubusercontent.com/46072451/158877659-fc88040f-2596-4782-aee1-e74452405c04.png)

<template>
  <QuillEditor :modules="modules" toolbar="full" :options="editorOption" />
</template>

<script>
import { QuillEditor, Quill } from "@vueup/vue-quill";
import BlotFormatter from "quill-blot-formatter";
import "@vueup/vue-quill/dist/vue-quill.snow.css";

import htmlEditButton from "quill-html-edit-button";

Quill.register("modules/htmlEditButton", htmlEditButton);
export default {
  components: {
    QuillEditor,
  },
  editorOption: {
    theme: "snow",
    modules: {
      toolbar: [
        ["bold", "italic", "underline", "strike"],
        ["blockquote", "code-block"],
        [{ header: 1 }, { header: 2 }],
        [{ list: "ordered" }, { list: "bullet" }],
        [{ script: "sub" }, { script: "super" }],
        [{ indent: "-1" }, { indent: "+1" }],
        [{ direction: "rtl" }],
        [{ size: ["small", false, "large", "huge"] }],
        [{ header: [1, 2, 3, 4, 5, 6, false] }],
        [{ color: [] }, { background: [] }],
        [{ font: [] }],
        [{ align: [] }],
        ["clean"],
        ["link", "image", "video"],
        ["htmlEditButton"],
      ],
      ImageResize: {},
      VideoResize: {},
      htmlEditButton: {
        debug: true,
        msg: "Edit the content in HTML format",
        okText: "Ok",
        cancelText: "Cancel",
        buttonHTML: "HTML",
        buttonTitle: "Show HTML source",
        syntax: false,
        prependSelector: "div#myelement",
        editorModules: {},
      },
    },
  },
  setup: () => {
    const modules = {
      name: "blotFormatter",
      module: BlotFormatter,
      options: {
        /* options */
      },
    };
    return { modules };
  },
};
</script>
``

**Comment by Taekondainc** [comment]
help
!!!!!!

**Comment by benwinding** [comment]
Hi @Taekondainc,
There's now an example on how to use this module with Vue3 here:
- [Vue Demo link](https://benwinding.github.io/quill-html-edit-button/vue/)
- [Demo source code](https://github.com/benwinding/quill-html-edit-button/blob/master/demos/vue)
Let me know if this helps you use the module
