### ISSUE TITLE
List elements deleted if lines of HTML have leading whitespace 

### ISSUE THREAD

**Issue by aberwristwatch** [benwinding/quill-html-edit-button#6]
The formatHTML function in quill.htmlEditButton.js is doing a good job of beautifying the raw HTML.
However for me when there is a list in the editor contents the leading whitespace before the `<li>` tag is causing the editor to lose the list when the OK button is clicked.

A solution that works for me is to remove newlines and trim each of the lines before joining them back together.
So I changed this 
`    const noNewlines = textArea.value.replace(/\r?\n/g, '');
    quill.container.querySelector(".ql-editor").innerHTML = noNewlines;`

with this

`    const output = textArea.value.split(/\r?\n/g).map(el => el.trim());
    quill.container.querySelector(".ql-editor").innerHTML = output.join('');`

**Comment by benwinding** [comment]
Thanks for reporting the issue @aberwristwatch,

Appreciate your solution too. It's fixed in version:`1.0.6`

Cheers,
Ben
