### ISSUE TITLE
Error in html edit button import 

### ISSUE THREAD

**Issue by mohamedsaad1989** [benwinding/quill-html-edit-button#62]
I work on an Angular project and I used the package, but recently the import into the component displays an error.
![image](https://user-images.githubusercontent.com/46066349/197500500-c65986d1-dd83-4594-b7ee-30a765c88a03.png)
please anyone have any idea about this

Thanks,

**Comment by nils1323** [comment]
small hack, replace `node_modules/quill-html-edit-button/types/index.d.ts` by:
``` 
import { QuillHtmlEditButtonOptions } from "options";
import { htmlEditButton } from "quill.htmlEditButton";
export { htmlEditButton, QuillHtmlEditButtonOptions };
```

It works in Vue.js for me.
