### ISSUE TITLE
How to work with ReactQuill?

### ISSUE THREAD

**Issue by dawnmessier** [benwinding/quill-html-edit-button#7]
I am using ReactQuill and need an html module. Installed this using `npm install quill-html-edit-button`. The went into component and tried different ways to get it imported into the component for use.

i tried `import {htmlEditButton} from 'quill-html-edit-button'` and `import HtmlEditButton from 'quill-html-edit-button'`

I updated the module property for ReactQuill component, like this

```
modules = {
    toolbar: [
      [{ header: [1, 2, 3, 4, false] }],
      ['bold', 'italic', 'underline', 'strike'],
      [{ list: 'ordered' }, { list: 'bullet' }, { align: [] }],
      ['link', 'image'],
      [{ color: [] }],
      [{htmlEditButton: {}}]
    ]
  }
```

But when i load the page, there is no button and a warning saying `quill:toolbar ignoring attaching to disabled format htmlEditButton`

does some kind of custom handler need to be created to make this button appear/work?

**Comment by dawnmessier** [comment]
Finally got it to work like this

```
import ReactQuill, { Quill } from 'react-quill';
import { htmlEditButton } from 'quill-html-edit-button';

Quill.register('modules/htmlEditButton', htmlEditButton);

modules = {
    toolbar: [
      [{ header: [1, 2, 3, 4, false] }],
      ['bold', 'italic', 'underline', 'strike'],
      [{ list: 'ordered' }, { list: 'bullet' }, { align: [] }],
      ['link', 'image'],
      [{ color: [] }]
    ],
    htmlEditButton: {}
  }
```

**Comment by benwinding** [comment]
Hey @dawnmessier,
Glad you got it working! Thanks for checking out the package and closing the issue

**Comment by saintfirewater** [comment]
@dawnmessier 
I use react-quill too. However I've got `ReferenceError: Quill is not defined` issue with your code.
Have you ever got issue like this?

\+ I saw the issue, [Quill is not defined](https://github.com/benwinding/quill-html-edit-button/issues/13)

**Comment by dawnmessier** [comment]
Could there be a compatibility issue with the version of the plugin and the react library?

**Comment by saintfirewater** [comment]
Well versions like below.
```
  "quill-html-edit-button": "^1.0.16",
  "react-quill": "^1.3.5",
  "react": "^16.13.1",
```

Could you let me know your version?

**Comment by dawnmessier** [comment]
from package-lock.json, mine is 

"react": "version": "16.13.1"
"quill": "version": "1.3.7"
"react-quill": "version": "1.3.5"
"quill-html-edit-button": "version": "1.0.16"

**Comment by Haris3243** [comment]
> @dawnmessier
> I use react-quill too. However I've got `ReferenceError: Quill is not defined` issue with your code.
> Have you ever got issue like this?
> 
> + I saw the issue, [Quill is not defined](https://github.com/benwinding/quill-html-edit-button/issues/13)

I am getting same Reference error: Quill is not defined.
I am using it in vue.js
@saintfirewater  any workaround ?? please help me

**Comment by SantiagoMC52** [comment]
> Finally got it to work like this
> 
> ```
> import ReactQuill, { Quill } from 'react-quill';
> import { htmlEditButton } from 'quill-html-edit-button';
> 
> Quill.register('modules/htmlEditButton', htmlEditButton);
> 
> modules = {
>     toolbar: [
>       [{ header: [1, 2, 3, 4, false] }],
>       ['bold', 'italic', 'underline', 'strike'],
>       [{ list: 'ordered' }, { list: 'bullet' }, { align: [] }],
>       ['link', 'image'],
>       [{ color: [] }]
>     ],
>     htmlEditButton: {}
>   }
> ```
