### ISSUE TITLE
Doesn't work on IE 11 (Nuxt.js)

### ISSUE THREAD

**Issue by saint777** [benwinding/quill-html-edit-button#9]
Hello, im using your plugin on Nuxt(vue), if you know theres 2 tasks (dev and build). When u run nuxt dev it throws error "IE11: Object doesn't support property or method 'forEach'"

```
import htmlEditButton from "quill-html-edit-button";
Quill.register("modules/htmlEditButton", htmlEditButton);
```

On build it's working ok, the nuxt can transpile your plugin, seems like the problem is with 'dist/quill.htmlEditButton.min.js'.

**Comment by benwinding** [comment]
Interesting, seems IE11 doesn't support that in specific cicumstances, seems this method fixes it

https://stackoverflow.com/questions/41142932/ie-supports-foreach-when-invoked-fromthe-console-but-not-when-called-from-t

Should be fixed now in `v1.0.8`
